services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: ${GLUETUN_CONTAINER_NAME:-gluetun}
    cap_add:
      - NET_ADMIN
      - NET_RAW
    ports:
      - "${HTTP_PROXY_BIND_IP:-127.0.0.1}:${HTTP_PROXY_BIND_PORT:-8888}:8888/tcp"
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - WIREGUARD_ENDPOINT_IP=${WIREGUARD_ENDPOINT_IP}
      - WIREGUARD_ENDPOINT_PORT=${WIREGUARD_ENDPOINT_PORT}
      - WIREGUARD_PUBLIC_KEY=${WIREGUARD_PUBLIC_KEY}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_PRESHARED_KEY=${WIREGUARD_PRESHARED_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - HTTPPROXY=on
      - HTTPPROXY_LOG=on
      - HTTPPROXY_STEALTH=on
      - TZ=${TZ:-Europe/Madrid}
    restart: unless-stopped
